version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/tri-target-bluegreen-ecs
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $ECR_URI:latest apps/ecs-web
      - docker push $ECR_URI:latest
      - jq ".executionRoleArn=\"${AWS_ECS_EXEC_ROLE_ARN}\" | .family=\"${ECS_FAMILY}\" | .containerDefinitions[0].image=\"$ECR_URI:latest\"" apps/ecs-web/taskdef.json > taskdef.out.json

artifacts:
  files:
    - apps/ecs-web/appspec-ecs.yaml
    - taskdef.out.json
  discard-paths: yes
